<a href="https://colab.research.google.com/github/Abdalrahmanhassan237/Pandas-Tutorials-for-Data-Analysis/blob/master/select_a_pandas_Series_from_a_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How To select a pandas Series from a DataFrame

In [1]:
import pandas as pd

In [6]:
ufo_data = pd .read_csv('https://bit.ly/uforeports')

In [9]:
ufo_data.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

# To select column from `DataFrame` use :
1 - `ufo_data['column name']`

2-  or use `ufo_data.column name`
* but in this method name of column should not seperated by space or not of dataframe attributes

In [11]:
ufo_data['Colors Reported']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
18236    NaN
18237    NaN
18238    NaN
18239    RED
18240    NaN
Name: Colors Reported, Length: 18241, dtype: object

In [12]:
ufo_data.City

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

# Add new series to **DataFrame** and fill with combining existing columns

In [16]:
ufo_data['location'] = ufo_data.City + " , "  + ufo_data.State
ufo_data

,City,Colors Reported,Shape Reported,State,Time,location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca , NY"
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro , NJ"
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke , CO"
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene , KS"
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair , NY"
...,...,...,...,...,...,...
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00,"Grant Park , IL"
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00,"Spirit Lake , IA"
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45,"Eagle River , WI"
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45,"Eagle River , WI"
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59,"Ybor , FL"